; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O3 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-SD
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O3 -global-isel -global-isel-abort=1 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-GI

; Ported from X86's tailccstack64.ll. The callee takes more integer arguments
; than fit in registers (x0-x7), so the last two are passed on the stack. The
; caller reorders them in the tail call (%in2 and %tmp swap stack slots), so the
; lowered stack arguments must not overwrite each other before the branch.

declare tailcc i32 @tailcallee(i32 %p1, i32 %p2, i32 %p3, i32 %p4, i32 %p5,
                               i32 %p6, i32 %p7, i32 %p8, i32 %a, i32 %b)

define tailcc i32 @tailcaller(i32 %p1, i32 %p2, i32 %p3, i32 %p4, i32 %p5,
; CHECK-SD-LABEL: tailcaller:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    ldr w8, [sp]
; CHECK-SD-NEXT:    ldr w9, [sp, #8]
; CHECK-SD-NEXT:    add w8, w8, w0
; CHECK-SD-NEXT:    str w9, [sp]
; CHECK-SD-NEXT:    str w8, [sp, #8]
; CHECK-SD-NEXT:    b tailcallee
;
; CHECK-GI-LABEL: tailcaller:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    ldr w8, [sp]
; CHECK-GI-NEXT:    ldr w9, [sp, #8]
; CHECK-GI-NEXT:    add w8, w8, w0
; CHECK-GI-NEXT:    str w9, [sp]
; CHECK-GI-NEXT:    str w8, [sp, #8]
; CHECK-GI-NEXT:    b tailcallee
                              i32 %p6, i32 %p7, i32 %p8, i32 %in1, i32 %in2) {
entry:
  %tmp = add i32 %in1, %p1
  %retval = tail call tailcc i32 @tailcallee(i32 %p1, i32 %p2, i32 %p3, i32 %p4,
                                             i32 %p5, i32 %p6, i32 %p7, i32 %p8,
                                             i32 %in2, i32 %tmp)
  ret i32 %retval
}
