; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O0 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-SD-O0
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O3 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-SD-O3
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O0 -global-isel -global-isel-abort=1 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-GI-O0
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O3 -global-isel -global-isel-abort=1 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-GI-O3

; A byval aggregate passed on the stack must have its outgoing-argument copy
; lowered as part of the tail call. When the source lives in the local frame or
; a global, the copy goes straight to the outgoing slot. When the source is the
; caller's own incoming argument area (a forwarded byval), the source may
; overlap the outgoing slot, so the copy is staged through a temporary in the
; local frame (see byValNeedsCopyForTailCall / OutgoingArgHandler). None of this
; is specific to tailcc: case E below is a plain C-calling-convention sibcall.

declare void @llvm.lifetime.start.p0(ptr nocapture)

declare tailcc i64 @callee(ptr byval([32 x i8]) align 8)
declare tailcc i64 @callee2(ptr byval([32 x i8]) align 8, ptr byval([32 x i8]) align 8)
declare tailcc i64 @callee3(i64, ptr byval([32 x i8]) align 8, i64)
declare i64 @callee_c(ptr byval([8 x i8]) align 8)
declare i64 @callee_c32(ptr byval([32 x i8]) align 8)

; Case A: byval built in a local alloca, guaranteed tail call (tailcc +
; musttail). The caller has no incoming stack area, so the frame is grown to
; hold the outgoing byval.
define tailcc i64 @from_alloca(i64 %a, i64 %d) {
; CHECK-SD-O0-LABEL: from_alloca:
; CHECK-SD-O0:       // %bb.0: // %start
; CHECK-SD-O0-NEXT:    sub sp, sp, #64
; CHECK-SD-O0-NEXT:    .cfi_def_cfa_offset 64
; CHECK-SD-O0-NEXT:    str x0, [sp]
; CHECK-SD-O0-NEXT:    mov x8, #-4919131752989213765 // =0xbbbbbbbbbbbbbbbb
; CHECK-SD-O0-NEXT:    str x8, [sp, #8]
; CHECK-SD-O0-NEXT:    mov x8, #-3689348814741910324 // =0xcccccccccccccccc
; CHECK-SD-O0-NEXT:    str x8, [sp, #16]
; CHECK-SD-O0-NEXT:    str x1, [sp, #24]
; CHECK-SD-O0-NEXT:    ldr q0, [sp]
; CHECK-SD-O0-NEXT:    str q0, [sp, #32]
; CHECK-SD-O0-NEXT:    ldr q0, [sp, #16]
; CHECK-SD-O0-NEXT:    str q0, [sp, #48]
; CHECK-SD-O0-NEXT:    add sp, sp, #32
; CHECK-SD-O0-NEXT:    b callee
;
; CHECK-SD-O3-LABEL: from_alloca:
; CHECK-SD-O3:       // %bb.0: // %start
; CHECK-SD-O3-NEXT:    mov x8, #-4919131752989213765 // =0xbbbbbbbbbbbbbbbb
; CHECK-SD-O3-NEXT:    stp x0, x8, [sp, #-64]!
; CHECK-SD-O3-NEXT:    .cfi_def_cfa_offset 64
; CHECK-SD-O3-NEXT:    mov x9, #-3689348814741910324 // =0xcccccccccccccccc
; CHECK-SD-O3-NEXT:    stp x9, x1, [sp, #16]
; CHECK-SD-O3-NEXT:    ldp q1, q0, [sp]
; CHECK-SD-O3-NEXT:    stp q1, q0, [sp, #32]!
; CHECK-SD-O3-NEXT:    b callee
;
; CHECK-GI-O0-LABEL: from_alloca:
; CHECK-GI-O0:       // %bb.0: // %start
; CHECK-GI-O0-NEXT:    sub sp, sp, #64
; CHECK-GI-O0-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-O0-NEXT:    str x0, [sp]
; CHECK-GI-O0-NEXT:    mov x8, #-4919131752989213765 // =0xbbbbbbbbbbbbbbbb
; CHECK-GI-O0-NEXT:    str x8, [sp, #8]
; CHECK-GI-O0-NEXT:    mov x8, #-3689348814741910324 // =0xcccccccccccccccc
; CHECK-GI-O0-NEXT:    str x8, [sp, #16]
; CHECK-GI-O0-NEXT:    str x1, [sp, #24]
; CHECK-GI-O0-NEXT:    ldr q0, [sp]
; CHECK-GI-O0-NEXT:    str q0, [sp, #32]
; CHECK-GI-O0-NEXT:    ldr q0, [sp, #16]
; CHECK-GI-O0-NEXT:    str q0, [sp, #48]
; CHECK-GI-O0-NEXT:    add sp, sp, #32
; CHECK-GI-O0-NEXT:    b callee
;
; CHECK-GI-O3-LABEL: from_alloca:
; CHECK-GI-O3:       // %bb.0: // %start
; CHECK-GI-O3-NEXT:    mov x8, #-4919131752989213765 // =0xbbbbbbbbbbbbbbbb
; CHECK-GI-O3-NEXT:    stp x0, x8, [sp, #-64]!
; CHECK-GI-O3-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-O3-NEXT:    mov x9, #-3689348814741910324 // =0xcccccccccccccccc
; CHECK-GI-O3-NEXT:    stp x9, x1, [sp, #16]
; CHECK-GI-O3-NEXT:    ldp q1, q0, [sp]
; CHECK-GI-O3-NEXT:    stp q1, q0, [sp, #32]!
; CHECK-GI-O3-NEXT:    b callee
start:
  %large = alloca [32 x i8], align 8
  call void @llvm.lifetime.start.p0(ptr nonnull %large)
  store i64 %a, ptr %large, align 8
  %0 = getelementptr inbounds nuw i8, ptr %large, i64 8
  store i64 -4919131752989213765, ptr %0, align 8
  %1 = getelementptr inbounds nuw i8, ptr %large, i64 16
  store i64 -3689348814741910324, ptr %1, align 8
  %2 = getelementptr inbounds nuw i8, ptr %large, i64 24
  store i64 %d, ptr %2, align 8
  %3 = musttail call tailcc i64 @callee(ptr byval([32 x i8]) align 8 %large)
  ret i64 %3
}

; Case B: byval sourced from a global constant.
@g = constant [32 x i8] c"\01\00\00\00\00\00\00\00\02\00\00\00\00\00\00\00\03\00\00\00\00\00\00\00\04\00\00\00\00\00\00\00"
define tailcc i64 @from_global() {
; CHECK-SD-O0-LABEL: from_global:
; CHECK-SD-O0:       // %bb.0:
; CHECK-SD-O0-NEXT:    sub sp, sp, #32
; CHECK-SD-O0-NEXT:    .cfi_def_cfa_offset 32
; CHECK-SD-O0-NEXT:    adrp x8, :got:g
; CHECK-SD-O0-NEXT:    ldr x8, [x8, :got_lo12:g]
; CHECK-SD-O0-NEXT:    ldr q0, [x8]
; CHECK-SD-O0-NEXT:    str q0, [sp]
; CHECK-SD-O0-NEXT:    ldr q0, [x8, #16]
; CHECK-SD-O0-NEXT:    str q0, [sp, #16]
; CHECK-SD-O0-NEXT:    b callee
;
; CHECK-SD-O3-LABEL: from_global:
; CHECK-SD-O3:       // %bb.0:
; CHECK-SD-O3-NEXT:    adrp x8, :got:g
; CHECK-SD-O3-NEXT:    ldr x8, [x8, :got_lo12:g]
; CHECK-SD-O3-NEXT:    ldr q0, [x8]
; CHECK-SD-O3-NEXT:    str q0, [sp, #-32]!
; CHECK-SD-O3-NEXT:    .cfi_def_cfa_offset 32
; CHECK-SD-O3-NEXT:    ldr q0, [x8, #16]
; CHECK-SD-O3-NEXT:    str q0, [sp, #16]
; CHECK-SD-O3-NEXT:    b callee
;
; CHECK-GI-O0-LABEL: from_global:
; CHECK-GI-O0:       // %bb.0:
; CHECK-GI-O0-NEXT:    sub sp, sp, #32
; CHECK-GI-O0-NEXT:    .cfi_def_cfa_offset 32
; CHECK-GI-O0-NEXT:    adrp x8, :got:g
; CHECK-GI-O0-NEXT:    ldr x8, [x8, :got_lo12:g]
; CHECK-GI-O0-NEXT:    ldr q0, [x8]
; CHECK-GI-O0-NEXT:    str q0, [sp]
; CHECK-GI-O0-NEXT:    ldr q0, [x8, #16]
; CHECK-GI-O0-NEXT:    str q0, [sp, #16]
; CHECK-GI-O0-NEXT:    b callee
;
; CHECK-GI-O3-LABEL: from_global:
; CHECK-GI-O3:       // %bb.0:
; CHECK-GI-O3-NEXT:    adrp x8, :got:g
; CHECK-GI-O3-NEXT:    ldr x8, [x8, :got_lo12:g]
; CHECK-GI-O3-NEXT:    ldr q0, [x8]
; CHECK-GI-O3-NEXT:    str q0, [sp, #-32]!
; CHECK-GI-O3-NEXT:    .cfi_def_cfa_offset 32
; CHECK-GI-O3-NEXT:    ldr q0, [x8, #16]
; CHECK-GI-O3-NEXT:    str q0, [sp, #16]
; CHECK-GI-O3-NEXT:    b callee
  %r = musttail call tailcc i64 @callee(ptr byval([32 x i8]) align 8 @g)
  ret i64 %r
}

; Case C: a byval interleaved with register arguments. The byval is built from
; a local so the caller itself has no byval argument.
define tailcc i64 @reg_byval_reg(i64 %x, i64 %y) {
; CHECK-SD-O0-LABEL: reg_byval_reg:
; CHECK-SD-O0:       // %bb.0:
; CHECK-SD-O0-NEXT:    sub sp, sp, #64
; CHECK-SD-O0-NEXT:    .cfi_def_cfa_offset 64
; CHECK-SD-O0-NEXT:    str x0, [sp]
; CHECK-SD-O0-NEXT:    ldr q0, [sp]
; CHECK-SD-O0-NEXT:    str q0, [sp, #32]
; CHECK-SD-O0-NEXT:    ldr q0, [sp, #16]
; CHECK-SD-O0-NEXT:    str q0, [sp, #48]
; CHECK-SD-O0-NEXT:    add sp, sp, #32
; CHECK-SD-O0-NEXT:    b callee3
;
; CHECK-SD-O3-LABEL: reg_byval_reg:
; CHECK-SD-O3:       // %bb.0:
; CHECK-SD-O3-NEXT:    str x0, [sp, #-64]!
; CHECK-SD-O3-NEXT:    .cfi_def_cfa_offset 64
; CHECK-SD-O3-NEXT:    ldp q1, q0, [sp]
; CHECK-SD-O3-NEXT:    stp q1, q0, [sp, #32]!
; CHECK-SD-O3-NEXT:    b callee3
;
; CHECK-GI-O0-LABEL: reg_byval_reg:
; CHECK-GI-O0:       // %bb.0:
; CHECK-GI-O0-NEXT:    sub sp, sp, #64
; CHECK-GI-O0-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-O0-NEXT:    str x0, [sp]
; CHECK-GI-O0-NEXT:    ldr q0, [sp]
; CHECK-GI-O0-NEXT:    str q0, [sp, #32]
; CHECK-GI-O0-NEXT:    ldr q0, [sp, #16]
; CHECK-GI-O0-NEXT:    str q0, [sp, #48]
; CHECK-GI-O0-NEXT:    add sp, sp, #32
; CHECK-GI-O0-NEXT:    b callee3
;
; CHECK-GI-O3-LABEL: reg_byval_reg:
; CHECK-GI-O3:       // %bb.0:
; CHECK-GI-O3-NEXT:    str x0, [sp, #-64]!
; CHECK-GI-O3-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-O3-NEXT:    ldp q1, q0, [sp]
; CHECK-GI-O3-NEXT:    stp q1, q0, [sp, #32]!
; CHECK-GI-O3-NEXT:    b callee3
  %buf = alloca [32 x i8], align 8
  store i64 %x, ptr %buf, align 8
  %r = musttail call tailcc i64 @callee3(i64 %x, ptr byval([32 x i8]) align 8 %buf, i64 %y)
  ret i64 %r
}

; Case D: two byval arguments, each built from a local.
define tailcc i64 @two_byval(i64 %x, i64 %y) {
; CHECK-SD-O0-LABEL: two_byval:
; CHECK-SD-O0:       // %bb.0:
; CHECK-SD-O0-NEXT:    sub sp, sp, #128
; CHECK-SD-O0-NEXT:    .cfi_def_cfa_offset 128
; CHECK-SD-O0-NEXT:    str x0, [sp, #32]
; CHECK-SD-O0-NEXT:    str x1, [sp]
; CHECK-SD-O0-NEXT:    ldr q0, [sp, #32]
; CHECK-SD-O0-NEXT:    str q0, [sp, #64]
; CHECK-SD-O0-NEXT:    ldr q0, [sp, #48]
; CHECK-SD-O0-NEXT:    str q0, [sp, #80]
; CHECK-SD-O0-NEXT:    ldr q0, [sp]
; CHECK-SD-O0-NEXT:    str q0, [sp, #96]
; CHECK-SD-O0-NEXT:    ldr q0, [sp, #16]
; CHECK-SD-O0-NEXT:    str q0, [sp, #112]
; CHECK-SD-O0-NEXT:    add sp, sp, #64
; CHECK-SD-O0-NEXT:    b callee2
;
; CHECK-SD-O3-LABEL: two_byval:
; CHECK-SD-O3:       // %bb.0:
; CHECK-SD-O3-NEXT:    sub sp, sp, #128
; CHECK-SD-O3-NEXT:    .cfi_def_cfa_offset 128
; CHECK-SD-O3-NEXT:    str x0, [sp, #32]
; CHECK-SD-O3-NEXT:    ldp q1, q0, [sp, #32]
; CHECK-SD-O3-NEXT:    str x1, [sp]
; CHECK-SD-O3-NEXT:    stp q1, q0, [sp, #64]
; CHECK-SD-O3-NEXT:    ldp q1, q0, [sp]
; CHECK-SD-O3-NEXT:    stp q1, q0, [sp, #96]
; CHECK-SD-O3-NEXT:    add sp, sp, #64
; CHECK-SD-O3-NEXT:    b callee2
;
; CHECK-GI-O0-LABEL: two_byval:
; CHECK-GI-O0:       // %bb.0:
; CHECK-GI-O0-NEXT:    sub sp, sp, #128
; CHECK-GI-O0-NEXT:    .cfi_def_cfa_offset 128
; CHECK-GI-O0-NEXT:    str x0, [sp, #32]
; CHECK-GI-O0-NEXT:    str x1, [sp]
; CHECK-GI-O0-NEXT:    ldr q0, [sp, #32]
; CHECK-GI-O0-NEXT:    str q0, [sp, #64]
; CHECK-GI-O0-NEXT:    ldr q0, [sp, #48]
; CHECK-GI-O0-NEXT:    str q0, [sp, #80]
; CHECK-GI-O0-NEXT:    ldr q0, [sp]
; CHECK-GI-O0-NEXT:    str q0, [sp, #96]
; CHECK-GI-O0-NEXT:    ldr q0, [sp, #16]
; CHECK-GI-O0-NEXT:    str q0, [sp, #112]
; CHECK-GI-O0-NEXT:    add sp, sp, #64
; CHECK-GI-O0-NEXT:    b callee2
;
; CHECK-GI-O3-LABEL: two_byval:
; CHECK-GI-O3:       // %bb.0:
; CHECK-GI-O3-NEXT:    sub sp, sp, #128
; CHECK-GI-O3-NEXT:    .cfi_def_cfa_offset 128
; CHECK-GI-O3-NEXT:    str x0, [sp, #32]
; CHECK-GI-O3-NEXT:    ldp q1, q0, [sp, #32]
; CHECK-GI-O3-NEXT:    str x1, [sp]
; CHECK-GI-O3-NEXT:    stp q1, q0, [sp, #64]
; CHECK-GI-O3-NEXT:    ldp q1, q0, [sp]
; CHECK-GI-O3-NEXT:    stp q1, q0, [sp, #96]
; CHECK-GI-O3-NEXT:    add sp, sp, #64
; CHECK-GI-O3-NEXT:    b callee2
  %p = alloca [32 x i8], align 8
  %q = alloca [32 x i8], align 8
  store i64 %x, ptr %p, align 8
  store i64 %y, ptr %q, align 8
  %r = musttail call tailcc i64 @callee2(ptr byval([32 x i8]) align 8 %p, ptr byval([32 x i8]) align 8 %q)
  ret i64 %r
}

; Case E: a plain C-calling-convention sibcall (no tailcc). The caller has an
; 8-byte incoming stack-argument area, so the 8-byte outgoing byval fits and the
; sibcall is performed. This exercises the same byval path without tailcc.
define i64 @ccc_sibcall_fits(i64 %a0, i64 %a1, i64 %a2, i64 %a3, i64 %a4, i64 %a5, i64 %a6, i64 %a7, i64 %s8) {
; CHECK-SD-O0-LABEL: ccc_sibcall_fits:
; CHECK-SD-O0:       // %bb.0:
; CHECK-SD-O0-NEXT:    sub sp, sp, #16
; CHECK-SD-O0-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-O0-NEXT:    ldr x8, [sp, #16]
; CHECK-SD-O0-NEXT:    str x8, [sp, #8]
; CHECK-SD-O0-NEXT:    ldr x8, [sp, #8]
; CHECK-SD-O0-NEXT:    str x8, [sp, #16]
; CHECK-SD-O0-NEXT:    add sp, sp, #16
; CHECK-SD-O0-NEXT:    b callee_c
;
; CHECK-SD-O3-LABEL: ccc_sibcall_fits:
; CHECK-SD-O3:       // %bb.0:
; CHECK-SD-O3-NEXT:    b callee_c
;
; CHECK-GI-O0-LABEL: ccc_sibcall_fits:
; CHECK-GI-O0:       // %bb.0:
; CHECK-GI-O0-NEXT:    sub sp, sp, #16
; CHECK-GI-O0-NEXT:    .cfi_def_cfa_offset 16
; CHECK-GI-O0-NEXT:    ldr x8, [sp, #16]
; CHECK-GI-O0-NEXT:    str x8, [sp, #8]
; CHECK-GI-O0-NEXT:    ldr x8, [sp, #8]
; CHECK-GI-O0-NEXT:    str x8, [sp, #16]
; CHECK-GI-O0-NEXT:    add sp, sp, #16
; CHECK-GI-O0-NEXT:    b callee_c
;
; CHECK-GI-O3-LABEL: ccc_sibcall_fits:
; CHECK-GI-O3:       // %bb.0:
; CHECK-GI-O3-NEXT:    sub sp, sp, #16
; CHECK-GI-O3-NEXT:    .cfi_def_cfa_offset 16
; CHECK-GI-O3-NEXT:    ldr x8, [sp, #16]
; CHECK-GI-O3-NEXT:    stp x8, x8, [sp, #8]
; CHECK-GI-O3-NEXT:    add sp, sp, #16
; CHECK-GI-O3-NEXT:    b callee_c
  %buf = alloca [8 x i8], align 8
  store i64 %s8, ptr %buf, align 8
  %r = tail call i64 @callee_c(ptr byval([8 x i8]) align 8 %buf)
  ret i64 %r
}

; Case F: forwarding an incoming byval argument unchanged. The source and the
; outgoing slot are at the same offset (NoCopy), so the forward is performed
; with no copy at all.
define tailcc i64 @forward_incoming(ptr byval([32 x i8]) align 8 %p) {
; CHECK-SD-O0-LABEL: forward_incoming:
; CHECK-SD-O0:       // %bb.0:
; CHECK-SD-O0-NEXT:    ldr q0, [sp]
; CHECK-SD-O0-NEXT:    str q0, [sp]
; CHECK-SD-O0-NEXT:    ldr q0, [sp, #16]
; CHECK-SD-O0-NEXT:    str q0, [sp, #16]
; CHECK-SD-O0-NEXT:    b callee
;
; CHECK-SD-O3-LABEL: forward_incoming:
; CHECK-SD-O3:       // %bb.0:
; CHECK-SD-O3-NEXT:    b callee
;
; CHECK-GI-O0-LABEL: forward_incoming:
; CHECK-GI-O0:       // %bb.0:
; CHECK-GI-O0-NEXT:    ldr q0, [sp]
; CHECK-GI-O0-NEXT:    str q0, [sp]
; CHECK-GI-O0-NEXT:    ldr q0, [sp, #16]
; CHECK-GI-O0-NEXT:    str q0, [sp, #16]
; CHECK-GI-O0-NEXT:    b callee
;
; CHECK-GI-O3-LABEL: forward_incoming:
; CHECK-GI-O3:       // %bb.0:
; CHECK-GI-O3-NEXT:    ldp q1, q0, [sp]
; CHECK-GI-O3-NEXT:    stp q1, q0, [sp]
; CHECK-GI-O3-NEXT:    b callee
  %r = tail call tailcc i64 @callee(ptr byval([32 x i8]) align 8 %p)
  ret i64 %r
}

; Case G (negative): a C-calling-convention tail call whose 32-byte outgoing
; byval does not fit the caller's (empty) incoming stack area, so it is demoted
; to an ordinary call.
define i64 @ccc_sibcall_nofit(i64 %a) {
; CHECK-SD-O0-LABEL: ccc_sibcall_nofit:
; CHECK-SD-O0:       // %bb.0:
; CHECK-SD-O0-NEXT:    sub sp, sp, #80
; CHECK-SD-O0-NEXT:    str x30, [sp, #64] // 8-byte Spill
; CHECK-SD-O0-NEXT:    .cfi_def_cfa_offset 80
; CHECK-SD-O0-NEXT:    .cfi_offset w30, -16
; CHECK-SD-O0-NEXT:    str x0, [sp, #32]
; CHECK-SD-O0-NEXT:    mov x8, sp
; CHECK-SD-O0-NEXT:    ldr q0, [sp, #32]
; CHECK-SD-O0-NEXT:    str q0, [x8]
; CHECK-SD-O0-NEXT:    ldr q0, [sp, #48]
; CHECK-SD-O0-NEXT:    str q0, [x8, #16]
; CHECK-SD-O0-NEXT:    bl callee_c32
; CHECK-SD-O0-NEXT:    ldr x30, [sp, #64] // 8-byte Reload
; CHECK-SD-O0-NEXT:    add sp, sp, #80
; CHECK-SD-O0-NEXT:    ret
;
; CHECK-SD-O3-LABEL: ccc_sibcall_nofit:
; CHECK-SD-O3:       // %bb.0:
; CHECK-SD-O3-NEXT:    sub sp, sp, #80
; CHECK-SD-O3-NEXT:    str x30, [sp, #64] // 8-byte Spill
; CHECK-SD-O3-NEXT:    .cfi_def_cfa_offset 80
; CHECK-SD-O3-NEXT:    .cfi_offset w30, -16
; CHECK-SD-O3-NEXT:    str x0, [sp, #32]
; CHECK-SD-O3-NEXT:    ldp q1, q0, [sp, #32]
; CHECK-SD-O3-NEXT:    stp q1, q0, [sp]
; CHECK-SD-O3-NEXT:    bl callee_c32
; CHECK-SD-O3-NEXT:    ldr x30, [sp, #64] // 8-byte Reload
; CHECK-SD-O3-NEXT:    add sp, sp, #80
; CHECK-SD-O3-NEXT:    ret
;
; CHECK-GI-O0-LABEL: ccc_sibcall_nofit:
; CHECK-GI-O0:       // %bb.0:
; CHECK-GI-O0-NEXT:    sub sp, sp, #80
; CHECK-GI-O0-NEXT:    str x30, [sp, #64] // 8-byte Spill
; CHECK-GI-O0-NEXT:    .cfi_def_cfa_offset 80
; CHECK-GI-O0-NEXT:    .cfi_offset w30, -16
; CHECK-GI-O0-NEXT:    str x0, [sp, #32]
; CHECK-GI-O0-NEXT:    mov x8, sp
; CHECK-GI-O0-NEXT:    ldr q0, [sp, #32]
; CHECK-GI-O0-NEXT:    str q0, [x8]
; CHECK-GI-O0-NEXT:    ldr q0, [sp, #48]
; CHECK-GI-O0-NEXT:    str q0, [x8, #16]
; CHECK-GI-O0-NEXT:    bl callee_c32
; CHECK-GI-O0-NEXT:    ldr x30, [sp, #64] // 8-byte Reload
; CHECK-GI-O0-NEXT:    add sp, sp, #80
; CHECK-GI-O0-NEXT:    ret
;
; CHECK-GI-O3-LABEL: ccc_sibcall_nofit:
; CHECK-GI-O3:       // %bb.0:
; CHECK-GI-O3-NEXT:    sub sp, sp, #80
; CHECK-GI-O3-NEXT:    str x30, [sp, #64] // 8-byte Spill
; CHECK-GI-O3-NEXT:    .cfi_def_cfa_offset 80
; CHECK-GI-O3-NEXT:    .cfi_offset w30, -16
; CHECK-GI-O3-NEXT:    str x0, [sp, #32]
; CHECK-GI-O3-NEXT:    ldp q0, q1, [sp, #32]
; CHECK-GI-O3-NEXT:    stp q0, q1, [sp]
; CHECK-GI-O3-NEXT:    bl callee_c32
; CHECK-GI-O3-NEXT:    ldr x30, [sp, #64] // 8-byte Reload
; CHECK-GI-O3-NEXT:    add sp, sp, #80
; CHECK-GI-O3-NEXT:    ret
  %buf = alloca [32 x i8], align 8
  store i64 %a, ptr %buf, align 8
  %r = tail call i64 @callee_c32(ptr byval([32 x i8]) align 8 %buf)
  ret i64 %r
}
