; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O3 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-SD
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O3 -global-isel -global-isel-abort=1 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-GI
;
; Only -O3 is exercised here: at -O0 the forwarded byval is conservatively
; staged through a temporary whose memcpy libcall trips a pre-existing
; machine-verifier issue with call-frame nesting, unrelated to this lowering.

; Ported from X86's tailccbyval64.ll. The caller itself receives a (large) byval
; argument and forwards it, by value, to the tail callee while also passing
; extra scalar arguments. The forwarded byval stays at the same stack offset
; (NoCopy), so it can be reused in place and the call is still a tail call.

%struct.s = type { i64, i64, i64, i64, i64, i64, i64, i64,
                   i64, i64, i64, i64, i64, i64, i64, i64,
                   i64, i64, i64, i64, i64, i64, i64, i64 }

declare tailcc i64 @tailcallee(ptr byval(%struct.s) %a, i64 %val, i64 %val2,
                               i64 %val3, i64 %val4, i64 %val5)

define tailcc i64 @tailcaller(i64 %b, ptr byval(%struct.s) %a) {
; CHECK-SD-LABEL: tailcaller:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    ldr x8, [sp, #8]
; CHECK-SD-NEXT:    mov x1, x0
; CHECK-SD-NEXT:    mov w2, #7 // =0x7
; CHECK-SD-NEXT:    mov w3, #13 // =0xd
; CHECK-SD-NEXT:    mov w4, #17 // =0x11
; CHECK-SD-NEXT:    mov x0, x8
; CHECK-SD-NEXT:    b tailcallee
;
; CHECK-GI-LABEL: tailcaller:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    ldp q1, q0, [sp]
; CHECK-GI-NEXT:    mov x1, x0
; CHECK-GI-NEXT:    ldr x8, [sp, #8]
; CHECK-GI-NEXT:    mov w2, #7 // =0x7
; CHECK-GI-NEXT:    mov w3, #13 // =0xd
; CHECK-GI-NEXT:    mov w4, #17 // =0x11
; CHECK-GI-NEXT:    stp q1, q0, [sp]
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #32]
; CHECK-GI-NEXT:    mov x0, x8
; CHECK-GI-NEXT:    stp q1, q0, [sp, #32]
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #64]
; CHECK-GI-NEXT:    stp q1, q0, [sp, #64]
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #96]
; CHECK-GI-NEXT:    stp q1, q0, [sp, #96]
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #128]
; CHECK-GI-NEXT:    stp q1, q0, [sp, #128]
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #160]
; CHECK-GI-NEXT:    stp q1, q0, [sp, #160]
; CHECK-GI-NEXT:    b tailcallee
entry:
  %tmp2 = getelementptr %struct.s, ptr %a, i32 0, i32 1
  %tmp3 = load i64, ptr %tmp2, align 8
  %tmp4 = tail call tailcc i64 @tailcallee(ptr byval(%struct.s) %a, i64 %tmp3,
                                           i64 %b, i64 7, i64 13, i64 17)
  ret i64 %tmp4
}

; Forwarding an incoming byval to a callee with an extra leading stack argument
; shifts the byval's offset, so the source (our incoming slot) and destination
; (the outgoing slot) partially overlap. A direct memcpy would clobber bytes it
; still has to read, so the source is staged through a temporary in the local
; frame. This is the case the staging logic exists for.
declare tailcc i64 @overlap_callee(i64, i64, i64, i64, i64, i64, i64, i64, i64,
                                   ptr byval([64 x i8]) align 8)

define tailcc i64 @forward_overlap(i64 %r0, i64 %r1, i64 %r2, i64 %r3, i64 %r4,
; CHECK-SD-LABEL: forward_overlap:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    sub sp, sp, #80
; CHECK-SD-NEXT:    .cfi_def_cfa_offset 80
; CHECK-SD-NEXT:    ldp q0, q1, [sp, #80]
; CHECK-SD-NEXT:    mov w8, #99 // =0x63
; CHECK-SD-NEXT:    str x8, [sp, #64]
; CHECK-SD-NEXT:    stp q0, q1, [sp]
; CHECK-SD-NEXT:    ldp q2, q1, [sp, #112]
; CHECK-SD-NEXT:    stur q0, [sp, #72]
; CHECK-SD-NEXT:    stp q2, q1, [sp, #32]
; CHECK-SD-NEXT:    stur q1, [sp, #120]
; CHECK-SD-NEXT:    ldp q1, q0, [sp, #16]
; CHECK-SD-NEXT:    stur q1, [sp, #88]
; CHECK-SD-NEXT:    stur q0, [sp, #104]
; CHECK-SD-NEXT:    add sp, sp, #64
; CHECK-SD-NEXT:    b overlap_callee
;
; CHECK-GI-LABEL: forward_overlap:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sub sp, sp, #80
; CHECK-GI-NEXT:    .cfi_def_cfa_offset 80
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #80]
; CHECK-GI-NEXT:    mov w8, #99 // =0x63
; CHECK-GI-NEXT:    str x8, [sp, #64]
; CHECK-GI-NEXT:    stp q1, q0, [sp]
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #112]
; CHECK-GI-NEXT:    stp q1, q0, [sp, #32]
; CHECK-GI-NEXT:    ldp q1, q0, [sp]
; CHECK-GI-NEXT:    stur q1, [sp, #72]
; CHECK-GI-NEXT:    stur q0, [sp, #88]
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #32]
; CHECK-GI-NEXT:    stur q1, [sp, #104]
; CHECK-GI-NEXT:    stur q0, [sp, #120]
; CHECK-GI-NEXT:    add sp, sp, #64
; CHECK-GI-NEXT:    b overlap_callee
                                   i64 %r5, i64 %r6, i64 %r7,
                                   ptr byval([64 x i8]) align 8 %p) {
  %r = musttail call tailcc i64 @overlap_callee(i64 %r0, i64 %r1, i64 %r2,
                                                i64 %r3, i64 %r4, i64 %r5,
                                                i64 %r6, i64 %r7, i64 99,
                                                ptr byval([64 x i8]) align 8 %p)
  ret i64 %r
}
