; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -verify-machineinstrs < %s -mtriple=aarch64-none-linux-gnu -tailcallopt | FileCheck %s --check-prefixes=SDAG,COMMON
; RUN: llc -global-isel -global-isel-abort=1 -verify-machineinstrs < %s -mtriple=aarch64-none-linux-gnu -tailcallopt | FileCheck %s --check-prefixes=GISEL,COMMON

declare fastcc void @callee_stack0()
declare fastcc void @callee_stack8([8 x i64], i64)
declare fastcc void @callee_stack16([8 x i64], i64, i64)
declare extern_weak fastcc void @callee_weak()

define fastcc void @caller_to0_from0() nounwind {
; SDAG-LABEL: caller_to0_from0:
; SDAG:       // %bb.0:
; SDAG-NEXT:    b callee_stack0
;
; GISEL-LABEL: caller_to0_from0:
; GISEL:       // %bb.0:
; GISEL-NEXT:    b callee_stack0

  tail call fastcc void @callee_stack0()
  ret void

}

define fastcc void @caller_to0_from8([8 x i64], i64) #0 {
; SDAG-LABEL: caller_to0_from8:
; SDAG:       // %bb.0:
; SDAG-NEXT:    add sp, sp, #16
; SDAG-NEXT:    .cfi_def_cfa_offset -16
; SDAG-NEXT:    b callee_stack0
;
; GISEL-LABEL: caller_to0_from8:
; GISEL:       // %bb.0:
; GISEL-NEXT:    add sp, sp, #16
; GISEL-NEXT:    .cfi_def_cfa_offset -16
; GISEL-NEXT:    b callee_stack0

  tail call fastcc void @callee_stack0()
  ret void

}

define fastcc void @caller_to8_from0() #0 {
; SDAG-LABEL: caller_to8_from0:
; SDAG:       // %bb.0:
; SDAG-NEXT:    mov w8, #42 // =0x2a
; SDAG-NEXT:    str x8, [sp, #-16]!
; SDAG-NEXT:    .cfi_def_cfa_offset 16
; SDAG-NEXT:    b callee_stack8
;
; GISEL-LABEL: caller_to8_from0:
; GISEL:       // %bb.0:
; GISEL-NEXT:    mov w8, #42 // =0x2a
; GISEL-NEXT:    str x8, [sp, #-16]!
; GISEL-NEXT:    .cfi_def_cfa_offset 16
; GISEL-NEXT:    b callee_stack8

; Key point is that the "42" should go #16 below incoming stack
; pointer (we didn't have arg space to reuse).
  tail call fastcc void @callee_stack8([8 x i64] undef, i64 42)
  ret void

}

define fastcc void @caller_to8_from8([8 x i64], i64 %a) #0 {
; SDAG-LABEL: caller_to8_from8:
; SDAG:       // %bb.0:
; SDAG-NEXT:    mov w8, #42 // =0x2a
; SDAG-NEXT:    str x8, [sp]
; SDAG-NEXT:    b callee_stack8
;
; GISEL-LABEL: caller_to8_from8:
; GISEL:       // %bb.0:
; GISEL-NEXT:    mov w8, #42 // =0x2a
; GISEL-NEXT:    str x8, [sp]
; GISEL-NEXT:    b callee_stack8

; Key point is that the "%a" should go where at SP on entry.
  tail call fastcc void @callee_stack8([8 x i64] undef, i64 42)
  ret void

}

define fastcc void @caller_to16_from8([8 x i64], i64 %a) #0 {
; SDAG-LABEL: caller_to16_from8:
; SDAG:       // %bb.0:
; SDAG-NEXT:    mov w8, #2 // =0x2
; SDAG-NEXT:    mov w9, #42 // =0x2a
; SDAG-NEXT:    stp x9, x8, [sp]
; SDAG-NEXT:    b callee_stack16
;
; GISEL-LABEL: caller_to16_from8:
; GISEL:       // %bb.0:
; GISEL-NEXT:    mov w8, #42 // =0x2a
; GISEL-NEXT:    mov w9, #2 // =0x2
; GISEL-NEXT:    stp x8, x9, [sp]
; GISEL-NEXT:    b callee_stack16

; Important point is that the call reuses the "dead" argument space
; above %a on the stack. If it tries to go below incoming-SP then the
; callee will not deallocate the space, even in fastcc.
  tail call fastcc void @callee_stack16([8 x i64] undef, i64 42, i64 2)

  ret void
}


define fastcc void @caller_to8_from24([8 x i64], i64 %a, i64 %b, i64 %c) #0 {
; SDAG-LABEL: caller_to8_from24:
; SDAG:       // %bb.0:
; SDAG-NEXT:    mov w8, #42 // =0x2a
; SDAG-NEXT:    str x8, [sp, #16]!
; SDAG-NEXT:    .cfi_def_cfa_offset -16
; SDAG-NEXT:    b callee_stack8
;
; GISEL-LABEL: caller_to8_from24:
; GISEL:       // %bb.0:
; GISEL-NEXT:    mov w8, #42 // =0x2a
; GISEL-NEXT:    str x8, [sp, #16]!
; GISEL-NEXT:    .cfi_def_cfa_offset -16
; GISEL-NEXT:    b callee_stack8

; Key point is that the "%a" should go where at #16 above SP on entry.
  tail call fastcc void @callee_stack8([8 x i64] undef, i64 42)
  ret void

}


define fastcc void @caller_to16_from16([8 x i64], i64 %a, i64 %b) #0 {
; SDAG-LABEL: caller_to16_from16:
; SDAG:       // %bb.0:
; SDAG-NEXT:    ldp x9, x8, [sp]
; SDAG-NEXT:    stp x8, x9, [sp]
; SDAG-NEXT:    b callee_stack16
;
; GISEL-LABEL: caller_to16_from16:
; GISEL:       // %bb.0:
; GISEL-NEXT:    ldp x8, x9, [sp]
; GISEL-NEXT:    stp x9, x8, [sp]
; GISEL-NEXT:    b callee_stack16

; Here we want to make sure that both loads happen before the stores:
; otherwise either %a or %b will be wrongly clobbered.
  tail call fastcc void @callee_stack16([8 x i64] undef, i64 %b, i64 %a)
  ret void

}

define fastcc void @disable_tail_calls() nounwind "disable-tail-calls"="true" {
; SDAG-LABEL: disable_tail_calls:
; SDAG:       // %bb.0:
; SDAG-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; SDAG-NEXT:    bl callee_stack0
; SDAG-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; SDAG-NEXT:    ret
;
; GISEL-LABEL: disable_tail_calls:
; GISEL:       // %bb.0:
; GISEL-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; GISEL-NEXT:    bl callee_stack0
; GISEL-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; GISEL-NEXT:    ret

  tail call fastcc void @callee_stack0()
  ret void

}

; Weakly-referenced extern functions cannot be tail-called, as AAELF does
; not define the behaviour of branch instructions to undefined weak symbols.
define fastcc void @caller_weak() #0 {
; SDAG-LABEL: caller_weak:
; SDAG:       // %bb.0:
; SDAG-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; SDAG-NEXT:    .cfi_def_cfa_offset 16
; SDAG-NEXT:    .cfi_offset w30, -16
; SDAG-NEXT:    bl callee_weak
; SDAG-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; SDAG-NEXT:    .cfi_def_cfa_offset 0
; SDAG-NEXT:    .cfi_restore w30
; SDAG-NEXT:    ret
;
; GISEL-LABEL: caller_weak:
; GISEL:       // %bb.0:
; GISEL-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; GISEL-NEXT:    .cfi_def_cfa_offset 16
; GISEL-NEXT:    .cfi_offset w30, -16
; GISEL-NEXT:    bl callee_weak
; GISEL-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; GISEL-NEXT:    .cfi_def_cfa_offset 0
; GISEL-NEXT:    .cfi_restore w30
; GISEL-NEXT:    ret
  tail call void @callee_weak()
  ret void
}

declare { [2 x float] } @get_vec2()

define { [3 x float] } @test_add_elem() #0 {
; SDAG-LABEL: test_add_elem:
; SDAG:       // %bb.0:
; SDAG-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; SDAG-NEXT:    .cfi_def_cfa_offset 16
; SDAG-NEXT:    .cfi_offset w30, -16
; SDAG-NEXT:    bl get_vec2
; SDAG-NEXT:    fmov s2, #1.00000000
; SDAG-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; SDAG-NEXT:    .cfi_def_cfa_offset 0
; SDAG-NEXT:    .cfi_restore w30
; SDAG-NEXT:    ret
;
; GISEL-LABEL: test_add_elem:
; GISEL:       // %bb.0:
; GISEL-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; GISEL-NEXT:    .cfi_def_cfa_offset 16
; GISEL-NEXT:    .cfi_offset w30, -16
; GISEL-NEXT:    bl get_vec2
; GISEL-NEXT:    fmov s2, #1.00000000
; GISEL-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; GISEL-NEXT:    .cfi_def_cfa_offset 0
; GISEL-NEXT:    .cfi_restore w30
; GISEL-NEXT:    ret

  %call = tail call { [2 x float] } @get_vec2()
  %arr = extractvalue { [2 x float] } %call, 0
  %arr.0 = extractvalue [2 x float] %arr, 0
  %arr.1 = extractvalue [2 x float] %arr, 1

  %res.0 = insertvalue { [3 x float] } undef, float %arr.0, 0, 0
  %res.01 = insertvalue { [3 x float] } %res.0, float %arr.1, 0, 1
  %res.012 = insertvalue { [3 x float] } %res.01, float 1.000000e+00, 0, 2
  ret { [3 x float] } %res.012
}

declare double @get_double()
define { double, [2 x double] } @test_mismatched_insert() #0 {
; SDAG-LABEL: test_mismatched_insert:
; SDAG:       // %bb.0:
; SDAG-NEXT:    stp d9, d8, [sp, #-32]! // 16-byte Folded Spill
; SDAG-NEXT:    .cfi_def_cfa_offset 32
; SDAG-NEXT:    str x30, [sp, #16] // 8-byte Spill
; SDAG-NEXT:    .cfi_offset w30, -16
; SDAG-NEXT:    .cfi_offset b8, -24
; SDAG-NEXT:    .cfi_offset b9, -32
; SDAG-NEXT:    bl get_double
; SDAG-NEXT:    fmov d8, d0
; SDAG-NEXT:    bl get_double
; SDAG-NEXT:    fmov d9, d0
; SDAG-NEXT:    bl get_double
; SDAG-NEXT:    ldr x30, [sp, #16] // 8-byte Reload
; SDAG-NEXT:    fmov d2, d0
; SDAG-NEXT:    fmov d0, d8
; SDAG-NEXT:    fmov d1, d9
; SDAG-NEXT:    ldp d9, d8, [sp], #32 // 16-byte Folded Reload
; SDAG-NEXT:    .cfi_def_cfa_offset 0
; SDAG-NEXT:    .cfi_restore w30
; SDAG-NEXT:    .cfi_restore b8
; SDAG-NEXT:    .cfi_restore b9
; SDAG-NEXT:    ret
;
; GISEL-LABEL: test_mismatched_insert:
; GISEL:       // %bb.0:
; GISEL-NEXT:    stp d9, d8, [sp, #-32]! // 16-byte Folded Spill
; GISEL-NEXT:    .cfi_def_cfa_offset 32
; GISEL-NEXT:    str x30, [sp, #16] // 8-byte Spill
; GISEL-NEXT:    .cfi_offset w30, -16
; GISEL-NEXT:    .cfi_offset b8, -24
; GISEL-NEXT:    .cfi_offset b9, -32
; GISEL-NEXT:    bl get_double
; GISEL-NEXT:    fmov d8, d0
; GISEL-NEXT:    bl get_double
; GISEL-NEXT:    fmov d9, d0
; GISEL-NEXT:    bl get_double
; GISEL-NEXT:    ldr x30, [sp, #16] // 8-byte Reload
; GISEL-NEXT:    fmov d2, d0
; GISEL-NEXT:    fmov d0, d8
; GISEL-NEXT:    fmov d1, d9
; GISEL-NEXT:    ldp d9, d8, [sp], #32 // 16-byte Folded Reload
; GISEL-NEXT:    .cfi_def_cfa_offset 0
; GISEL-NEXT:    .cfi_restore w30
; GISEL-NEXT:    .cfi_restore b8
; GISEL-NEXT:    .cfi_restore b9
; GISEL-NEXT:    ret

  %val0 = call double @get_double()
  %val1 = call double @get_double()
  %val2 = tail call double @get_double()

  %res.0 = insertvalue { double, [2 x double] } undef, double %val0, 0
  %res.01 = insertvalue { double, [2 x double] } %res.0, double %val1, 1, 0
  %res.012 = insertvalue { double, [2 x double] } %res.01, double %val2, 1, 1

  ret { double, [2 x double] } %res.012
}

define tailcc noundef i64 @call_with_byval_caller(i64 noundef %a, i64 noundef %d) {
; SDAG-LABEL: call_with_byval_caller:
; SDAG:       // %bb.0: // %start
; SDAG-NEXT:    mov x8, #-4919131752989213765 // =0xbbbbbbbbbbbbbbbb
; SDAG-NEXT:    stp x0, x8, [sp, #-64]!
; SDAG-NEXT:    .cfi_def_cfa_offset 64
; SDAG-NEXT:    mov x9, #-3689348814741910324 // =0xcccccccccccccccc
; SDAG-NEXT:    stp x9, x1, [sp, #16]
; SDAG-NEXT:    ldp q1, q0, [sp]
; SDAG-NEXT:    stp q1, q0, [sp, #32]!
; SDAG-NEXT:    b call_with_byval_callee
;
; GISEL-LABEL: call_with_byval_caller:
; GISEL:       // %bb.0: // %start
; GISEL-NEXT:    mov x8, #-4919131752989213765 // =0xbbbbbbbbbbbbbbbb
; GISEL-NEXT:    stp x0, x8, [sp, #-64]!
; GISEL-NEXT:    .cfi_def_cfa_offset 64
; GISEL-NEXT:    mov x9, #-3689348814741910324 // =0xcccccccccccccccc
; GISEL-NEXT:    stp x9, x1, [sp, #16]
; GISEL-NEXT:    ldp q1, q0, [sp]
; GISEL-NEXT:    stp q1, q0, [sp, #32]!
; GISEL-NEXT:    b call_with_byval_callee
start:
  %large = alloca [32 x i8], align 8
  call void @llvm.lifetime.start.p0(ptr nonnull %large)
  store i64 %a, ptr %large, align 8
  %0 = getelementptr inbounds nuw i8, ptr %large, i64 8
  store i64 -4919131752989213765, ptr %0, align 8
  %1 = getelementptr inbounds nuw i8, ptr %large, i64 16
  store i64 -3689348814741910324, ptr %1, align 8
  %2 = getelementptr inbounds nuw i8, ptr %large, i64 24
  store i64 %d, ptr %2, align 8
  %3 = musttail call tailcc i64 @call_with_byval_callee(ptr byval([32 x i8]) %large)
  ret i64 %3
}

declare tailcc noundef i64 @call_with_byval_callee(ptr byval([32 x i8]) %large)

attributes #0 = { uwtable }
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; COMMON: {{.*}}
